---
- hosts: localhost
  tasks:

    - name: Generar número aleatorio entre 0 y 20
      shell: "shuf -i 0-20 -n 1"
      register: random_number

    - name: Guardar numero aleatorio
      copy:
        content: "{{ random_number.stdout }}"
        dest: "{{ playbook_dir }}/random_number.txt"
      notify:
        - Número es menor que 10
        - Número es mayor que 10

  handlers:
    - name: Número es mayor que 10
      copy:
        content: "El número es mayor que 10."
        dest: "{{ playbook_dir }}/message.txt"
      when: "random_number.stdout|int > 10"

    - name: Número es menor que 10
      copy:
        content: "El número es menor que 10."
        dest: "{{ playbook_dir }}/message.txt"
      when: random_number.stdout|int < 10
     
